--
-- ER/Studio 8.0 SQL Code Generation
-- Company :      a
-- Project :      e-market_3.DM1
-- Author :       a
--
-- Date Created : Saturday, January 21, 2023 21:29:36
-- Target DBMS : Oracle 11g
--

-- 
-- TABLE: CATEGORIA 
--

CREATE TABLE CATEGORIA(
    CATEGORIA_ID    NUMBER(2, 0)    NOT NULL,
    NOMBRE          VARCHAR2(15)    NOT NULL,
    CONSTRAINT PK4 PRIMARY KEY (CATEGORIA_ID)
    USING INDEX
TABLESPACE tablespace2
        LOGGING
        STORAGE(INITIAL 1K
                NEXT 2K
                )
)
TABLESPACE tablespace1
LOGGING
STORAGE(INITIAL 1K
        NEXT 2K
        )
;



-- 
-- TABLE: COMPRADOR 
--

CREATE TABLE COMPRADOR(
    COMPRADOR_ID    NUMBER(8, 0)     NOT NULL,
    DESCRIPCION     VARCHAR2(200)    NOT NULL,
    TELEFONO        VARCHAR2(12)     NOT NULL,
    OCUPACION_ID    NUMBER(4, 0)     NOT NULL,
    CONSTRAINT PK2 PRIMARY KEY (COMPRADOR_ID)
    USING INDEX
TABLESPACE tablespace2
        LOGGING
        STORAGE(INITIAL 1K
                NEXT 2K
                )
)
TABLESPACE tablespace1
LOGGING
STORAGE(INITIAL 1K
        NEXT 2K
        )
;



-- 
-- TABLE: ENCUESTA_SATISFACCION 
--

CREATE TABLE ENCUESTA_SATISFACCION(
    ENCUESTA_SATISFACCION_ID    NUMBER(12, 0)    NOT NULL,
    COMENTARIOS                 VARCHAR2(200)    NOT NULL,
    CALIFICACION                NUMBER(1, 0)     NOT NULL,
    FACTURA_ID                  NUMBER(12, 0)    NOT NULL,
    VENDEDOR_ID                 NUMBER(8, 0)     NOT NULL,
    CONSTRAINT PK17 PRIMARY KEY (ENCUESTA_SATISFACCION_ID)
    USING INDEX
TABLESPACE tablespace2
        LOGGING
        STORAGE(INITIAL 1K
                NEXT 2K
                )
)
TABLESPACE tablespace1
LOGGING
STORAGE(INITIAL 1K
        NEXT 2K
        )
;



-- 
-- TABLE: ESTATUS_PRODUCTO 
--

CREATE TABLE ESTATUS_PRODUCTO(
    ESTATUS_PRODUCTO_ID    NUMBER(2, 0)    NOT NULL,
    NOMBRE                 VARCHAR2(15)    NOT NULL,
    CONSTRAINT PK6 PRIMARY KEY (ESTATUS_PRODUCTO_ID)
    USING INDEX
TABLESPACE tablespace2
        LOGGING
        STORAGE(INITIAL 1K
                NEXT 2K
                )
)
TABLESPACE tablespace1
LOGGING
STORAGE(INITIAL 1K
        NEXT 2K
        )
;



-- 
-- TABLE: FACTURA 
--

CREATE TABLE FACTURA(
    FACTURA_ID            NUMBER(12, 0)    NOT NULL,
    FECHA_UBICACION       TIMESTAMP(6)     NOT NULL,
    FOLIO                 VARCHAR2(6)      NOT NULL,
    COMISION              NUMBER(5, 2)     NOT NULL,
    ORDEN_DE_COMPRA_ID    NUMBER(12, 0)    NOT NULL,
    PAQUETERIA_ID         NUMBER(2, 0)     NOT NULL,
    CONSTRAINT PK16 PRIMARY KEY (FACTURA_ID)
    USING INDEX
TABLESPACE tablespace2
        LOGGING
        STORAGE(INITIAL 1K
                NEXT 2K
                )
)
TABLESPACE tablespace1
LOGGING
STORAGE(INITIAL 1K
        NEXT 2K
        )
;



-- 
-- TABLE: FOTO_PRODUCTO 
--

CREATE TABLE FOTO_PRODUCTO(
    NUM_FOTO_PRODUCTO    NUMBER(2, 0)     NOT NULL,
    PRODUCTO_ID          NUMBER(10, 0)    NOT NULL,
    FOTO                 BLOB             NOT NULL,
    CONSTRAINT PK8 PRIMARY KEY (NUM_FOTO_PRODUCTO, PRODUCTO_ID)
    USING INDEX
TABLESPACE tablespace2
        LOGGING
        STORAGE(INITIAL 1K
                NEXT 2K
                )
)
TABLESPACE tablespace1
LOGGING
STORAGE(INITIAL 1K
        NEXT 2K
        )
;



-- 
-- TABLE: HISTORICO_ESTATUS_PRODUCTO 
--

CREATE TABLE HISTORICO_ESTATUS_PRODUCTO(
    HISTORICO_ESTATUS_PRODUCTO    NUMBER(11, 0)    NOT NULL,
    FECHA_ESTATUS                 TIMESTAMP(6)     NOT NULL,
    ESTATUS_PRODUCTO_ID           NUMBER(2, 0)     NOT NULL,
    PRODUCTO_ID                   NUMBER(10, 0)    NOT NULL,
    CONSTRAINT PK7 PRIMARY KEY (HISTORICO_ESTATUS_PRODUCTO)
    USING INDEX
TABLESPACE tablespace2
        LOGGING
        STORAGE(INITIAL 1K
                NEXT 2K
                )
)
TABLESPACE tablespace1
LOGGING
STORAGE(INITIAL 1K
        NEXT 2K
        )
;



-- 
-- TABLE: OCUPACION 
--

CREATE TABLE OCUPACION(
    OCUPACION_ID    NUMBER(4, 0)    NOT NULL,
    NOMBRE          VARCHAR2(25)    NOT NULL,
    CONSTRAINT PK18 PRIMARY KEY (OCUPACION_ID)
    USING INDEX
TABLESPACE tablespace2
        LOGGING
        STORAGE(INITIAL 1K
                NEXT 2K
                )
)
TABLESPACE tablespace1
LOGGING
STORAGE(INITIAL 1K
        NEXT 2K
        )
;



-- 
-- TABLE: OFERTA 
--

CREATE TABLE OFERTA(
    OFERTA_ID             NUMBER(15, 0)    NOT NULL,
    IMPORTE               NUMBER(9, 2)     NOT NULL,
    FECHA                 TIMESTAMP(6)     NOT NULL,
    ES_GANADORA           NUMBER(1, 0)     NOT NULL,
    COMPRADOR_ID          NUMBER(8, 0)     NOT NULL,
    PRODUCTO_ID           NUMBER(10, 0)    NOT NULL,
    SUBASTA_ID            NUMBER(6, 0),
    ORDEN_DE_COMPRA_ID    NUMBER(12, 0),
    CONSTRAINT PK14 PRIMARY KEY (OFERTA_ID)
    USING INDEX
TABLESPACE tablespace2
        LOGGING
        STORAGE(INITIAL 1K
                NEXT 2K
                )
)
TABLESPACE tablespace1
LOGGING
STORAGE(INITIAL 1K
        NEXT 2K
        )
;



-- 
-- TABLE: ORDEN_DE_COMPRA 
--

CREATE TABLE ORDEN_DE_COMPRA(
    ORDEN_DE_COMPRA_ID    NUMBER(12, 0)    NOT NULL,
    FECHA                 TIMESTAMP(6)     NOT NULL,
    TIPO_PAGO             CHAR(1)          NOT NULL,
    DIRECCION             VARCHAR2(150)    NOT NULL,
    TARJETA_ID            NUMBER(9, 0)     NOT NULL,
    CONSTRAINT PK12 PRIMARY KEY (ORDEN_DE_COMPRA_ID)
    USING INDEX
TABLESPACE tablespace2
        LOGGING
        STORAGE(INITIAL 1K
                NEXT 2K
                )
)
TABLESPACE tablespace1
LOGGING
STORAGE(INITIAL 1K
        NEXT 2K
        )
;



-- 
-- TABLE: PAQUETERIA 
--

CREATE TABLE PAQUETERIA(
    PAQUETERIA_ID    NUMBER(2, 0)    NOT NULL,
    NOMBRE           VARCHAR2(20)    NOT NULL,
    CONSTRAINT PK15 PRIMARY KEY (PAQUETERIA_ID)
    USING INDEX
TABLESPACE tablespace2
        LOGGING
        STORAGE(INITIAL 1K
                NEXT 2K
                )
)
TABLESPACE tablespace1
LOGGING
STORAGE(INITIAL 1K
        NEXT 2K
        )
;



-- 
-- TABLE: PRODUCTO 
--

CREATE TABLE PRODUCTO(
    PRODUCTO_ID            NUMBER(10, 0)    NOT NULL,
    NOMBRE                 VARCHAR2(30)     NOT NULL,
    DESCRIPCION            VARCHAR2(200)    NOT NULL,
    PRECIO_INICIAL         NUMBER(9, 2)     NOT NULL,
    FECHA_UTIL             DATE             NOT NULL,
    DEFECTOS               VARCHAR2(200)    NOT NULL,
    TIENE_DEFECTO          NUMBER(1, 0)     NOT NULL,
    FECHA_ESTATUS          TIMESTAMP(6)     NOT NULL,
    VENDEDOR_ID            NUMBER(8, 0)     NOT NULL,
    CATEGORIA_ID           NUMBER(2, 0)     NOT NULL,
    ESTATUS_PRODUCTO_ID    NUMBER(2, 0)     NOT NULL,
    CONSTRAINT PK5 PRIMARY KEY (PRODUCTO_ID)
    USING INDEX
TABLESPACE tablespace2
        LOGGING
        STORAGE(INITIAL 1K
                NEXT 2K
                )
)
TABLESPACE tablespace1
LOGGING
STORAGE(INITIAL 1K
        NEXT 2K
        )
;



-- 
-- TABLE: SUBASTA 
--

CREATE TABLE SUBASTA(
    SUBASTA_ID         NUMBER(6, 0)    NOT NULL,
    FECHA_INICIO       TIMESTAMP(6)    NOT NULL,
    FECHA_FIN          TIMESTAMP(6)    NOT NULL,
    TOTAL_PRODUCTOS    NUMBER(3, 0)    NOT NULL,
    CONSTRAINT PK10 PRIMARY KEY (SUBASTA_ID)
    USING INDEX
TABLESPACE tablespace2
        LOGGING
        STORAGE(INITIAL 1K
                NEXT 2K
                )
)
TABLESPACE tablespace1
LOGGING
STORAGE(INITIAL 1K
        NEXT 2K
        )
;



-- 
-- TABLE: TARJETA 
--

CREATE TABLE TARJETA(
    TARJETA_ID      NUMBER(9, 0)    NOT NULL,
    BANCO           VARCHAR2(20)    NOT NULL,
    NUMERO          CHAR(16)        NOT NULL,
    FECHA_EXP       DATE            NOT NULL,
    CVV             CHAR(3)         NOT NULL,
    COMPRADOR_ID    NUMBER(8, 0)    NOT NULL,
    CONSTRAINT PK13 PRIMARY KEY (TARJETA_ID)
    USING INDEX
TABLESPACE tablespace2
        LOGGING
        STORAGE(INITIAL 1K
                NEXT 2K
                )
)
TABLESPACE tablespace1
LOGGING
STORAGE(INITIAL 1K
        NEXT 2K
        )
;



-- 
-- TABLE: UBICACION_PAQUETE 
--

CREATE TABLE UBICACION_PAQUETE(
    UBICACION_PAQUETE_ID    NUMBER(15, 0)    NOT NULL,
    LATITUD                 NUMBER(6, 4)     NOT NULL,
    LONGITUD                NUMBER(6, 4)     NOT NULL,
    FECHA_UBICACION         TIMESTAMP(6)     NOT NULL,
    FACTURA_ID              NUMBER(12, 0)    NOT NULL,
    CONSTRAINT PK19 PRIMARY KEY (UBICACION_PAQUETE_ID)
    USING INDEX
TABLESPACE tablespace2
        LOGGING
        STORAGE(INITIAL 1K
                NEXT 2K
                )
)
TABLESPACE tablespace1
LOGGING
STORAGE(INITIAL 1K
        NEXT 2K
        )
;



-- 
-- TABLE: USUARIO 
--

CREATE TABLE USUARIO(
    USUARIO_ID        NUMBER(8, 0)    NOT NULL,
    NOMBRE            VARCHAR2(30)    NOT NULL,
    AP_PATERNO        VARCHAR2(30)    NOT NULL,
    AP_MATERNO        VARCHAR2(30)    NOT NULL,
    RFC               CHAR(13)        NOT NULL,
    FOTO              BLOB            NOT NULL,
    FECHA_REGISTRO    TIMESTAMP(6)    NOT NULL,
    EMAIL             VARCHAR2(35)    NOT NULL,
    USERNAME          VARCHAR2(20)    NOT NULL,
    PASSWORD          VARCHAR2(40)    NOT NULL,
    ES_VENDEDOR       NUMBER(1, 0)    NOT NULL,
    ES_COMPRADOR      NUMBER(1, 0)    NOT NULL,
    CONSTRAINT PK1 PRIMARY KEY (USUARIO_ID)
    USING INDEX
TABLESPACE tablespace2
        LOGGING
        STORAGE(INITIAL 1K
                NEXT 2K
                )
)
TABLESPACE tablespace1
LOGGING
STORAGE(INITIAL 1K
        NEXT 2K
        )
;



-- 
-- TABLE: VENDEDOR 
--

CREATE TABLE VENDEDOR(
    VENDEDOR_ID     NUMBER(8, 0)     NOT NULL,
    TIPO            CHAR(1)          NOT NULL,
    CALIFICACION    NUMBER(4, 2)     NOT NULL,
    DIRECCION       VARCHAR2(150)    NOT NULL,
    CONSTRAINT PK3 PRIMARY KEY (VENDEDOR_ID)
    USING INDEX
TABLESPACE tablespace2
        LOGGING
        STORAGE(INITIAL 1K
                NEXT 2K
                )
)
TABLESPACE tablespace1
LOGGING
STORAGE(INITIAL 1K
        NEXT 2K
        )
;



-- 
-- TABLE: VIDEO_PRODUCTO 
--

CREATE TABLE VIDEO_PRODUCTO(
    PRODUCTO_ID    NUMBER(10, 0)    NOT NULL,
    VIDEO          BLOB             NOT NULL,
    CONSTRAINT PK9 PRIMARY KEY (PRODUCTO_ID)
    USING INDEX
TABLESPACE tablespace2
        LOGGING
        STORAGE(INITIAL 1K
                NEXT 2K
                )
)
TABLESPACE tablespace1
LOGGING
STORAGE(INITIAL 1K
        NEXT 2K
        )
;



-- 
-- INDEX: Ref12 
--

CREATE INDEX Ref12 ON COMPRADOR(COMPRADOR_ID)
TABLESPACE tablespace2
    LOGGING
    STORAGE(INITIAL 1K
            NEXT 2K
            )
;
-- 
-- INDEX: Ref184 
--

CREATE INDEX Ref184 ON COMPRADOR(OCUPACION_ID)
TABLESPACE tablespace2
    LOGGING
    STORAGE(INITIAL 1K
            NEXT 2K
            )
;
-- 
-- INDEX: Ref1622 
--

CREATE INDEX Ref1622 ON ENCUESTA_SATISFACCION(FACTURA_ID)
TABLESPACE tablespace2
    LOGGING
    STORAGE(INITIAL 1K
            NEXT 2K
            )
;
-- 
-- INDEX: Ref325 
--

CREATE INDEX Ref325 ON ENCUESTA_SATISFACCION(VENDEDOR_ID)
TABLESPACE tablespace2
    LOGGING
    STORAGE(INITIAL 1K
            NEXT 2K
            )
;
-- 
-- INDEX: Ref1219 
--

CREATE INDEX Ref1219 ON FACTURA(ORDEN_DE_COMPRA_ID)
TABLESPACE tablespace2
    LOGGING
    STORAGE(INITIAL 1K
            NEXT 2K
            )
;
-- 
-- INDEX: Ref1521 
--

CREATE INDEX Ref1521 ON FACTURA(PAQUETERIA_ID)
TABLESPACE tablespace2
    LOGGING
    STORAGE(INITIAL 1K
            NEXT 2K
            )
;
-- 
-- INDEX: Ref511 
--

CREATE INDEX Ref511 ON FOTO_PRODUCTO(PRODUCTO_ID)
TABLESPACE tablespace2
    LOGGING
    STORAGE(INITIAL 1K
            NEXT 2K
            )
;
-- 
-- INDEX: Ref68 
--

CREATE INDEX Ref68 ON HISTORICO_ESTATUS_PRODUCTO(ESTATUS_PRODUCTO_ID)
TABLESPACE tablespace2
    LOGGING
    STORAGE(INITIAL 1K
            NEXT 2K
            )
;
-- 
-- INDEX: Ref59 
--

CREATE INDEX Ref59 ON HISTORICO_ESTATUS_PRODUCTO(PRODUCTO_ID)
TABLESPACE tablespace2
    LOGGING
    STORAGE(INITIAL 1K
            NEXT 2K
            )
;
-- 
-- INDEX: Ref215 
--

CREATE INDEX Ref215 ON OFERTA(COMPRADOR_ID)
TABLESPACE tablespace2
    LOGGING
    STORAGE(INITIAL 1K
            NEXT 2K
            )
;
-- 
-- INDEX: Ref516 
--

CREATE INDEX Ref516 ON OFERTA(PRODUCTO_ID)
TABLESPACE tablespace2
    LOGGING
    STORAGE(INITIAL 1K
            NEXT 2K
            )
;
-- 
-- INDEX: Ref1027 
--

CREATE INDEX Ref1027 ON OFERTA(SUBASTA_ID)
TABLESPACE tablespace2
    LOGGING
    STORAGE(INITIAL 1K
            NEXT 2K
            )
;
-- 
-- INDEX: Ref1228 
--

CREATE INDEX Ref1228 ON OFERTA(ORDEN_DE_COMPRA_ID)
TABLESPACE tablespace2
    LOGGING
    STORAGE(INITIAL 1K
            NEXT 2K
            )
;
-- 
-- INDEX: Ref1318 
--

CREATE INDEX Ref1318 ON ORDEN_DE_COMPRA(TARJETA_ID)
TABLESPACE tablespace2
    LOGGING
    STORAGE(INITIAL 1K
            NEXT 2K
            )
;
-- 
-- INDEX: Ref36 
--

CREATE INDEX Ref36 ON PRODUCTO(VENDEDOR_ID)
TABLESPACE tablespace2
    LOGGING
    STORAGE(INITIAL 1K
            NEXT 2K
            )
;
-- 
-- INDEX: Ref47 
--

CREATE INDEX Ref47 ON PRODUCTO(CATEGORIA_ID)
TABLESPACE tablespace2
    LOGGING
    STORAGE(INITIAL 1K
            NEXT 2K
            )
;
-- 
-- INDEX: Ref610 
--

CREATE INDEX Ref610 ON PRODUCTO(ESTATUS_PRODUCTO_ID)
TABLESPACE tablespace2
    LOGGING
    STORAGE(INITIAL 1K
            NEXT 2K
            )
;
-- 
-- INDEX: Ref25 
--

CREATE INDEX Ref25 ON TARJETA(COMPRADOR_ID)
TABLESPACE tablespace2
    LOGGING
    STORAGE(INITIAL 1K
            NEXT 2K
            )
;
-- 
-- INDEX: Ref1620 
--

CREATE INDEX Ref1620 ON UBICACION_PAQUETE(FACTURA_ID)
TABLESPACE tablespace2
    LOGGING
    STORAGE(INITIAL 1K
            NEXT 2K
            )
;
-- 
-- INDEX: Ref11 
--

CREATE INDEX Ref11 ON VENDEDOR(VENDEDOR_ID)
TABLESPACE tablespace2
    LOGGING
    STORAGE(INITIAL 1K
            NEXT 2K
            )
;
-- 
-- INDEX: Ref512 
--

CREATE INDEX Ref512 ON VIDEO_PRODUCTO(PRODUCTO_ID)
TABLESPACE tablespace2
    LOGGING
    STORAGE(INITIAL 1K
            NEXT 2K
            )
;
-- 
-- TABLE: COMPRADOR 
--

ALTER TABLE COMPRADOR ADD CONSTRAINT RefUSUARIO2 
    FOREIGN KEY (COMPRADOR_ID)
    REFERENCES USUARIO(USUARIO_ID)
;

ALTER TABLE COMPRADOR ADD CONSTRAINT RefOCUPACION4 
    FOREIGN KEY (OCUPACION_ID)
    REFERENCES OCUPACION(OCUPACION_ID)
;


-- 
-- TABLE: ENCUESTA_SATISFACCION 
--

ALTER TABLE ENCUESTA_SATISFACCION ADD CONSTRAINT RefFACTURA22 
    FOREIGN KEY (FACTURA_ID)
    REFERENCES FACTURA(FACTURA_ID)
;

ALTER TABLE ENCUESTA_SATISFACCION ADD CONSTRAINT RefVENDEDOR25 
    FOREIGN KEY (VENDEDOR_ID)
    REFERENCES VENDEDOR(VENDEDOR_ID)
;


-- 
-- TABLE: FACTURA 
--

ALTER TABLE FACTURA ADD CONSTRAINT RefORDEN_DE_COMPRA19 
    FOREIGN KEY (ORDEN_DE_COMPRA_ID)
    REFERENCES ORDEN_DE_COMPRA(ORDEN_DE_COMPRA_ID)
;

ALTER TABLE FACTURA ADD CONSTRAINT RefPAQUETERIA21 
    FOREIGN KEY (PAQUETERIA_ID)
    REFERENCES PAQUETERIA(PAQUETERIA_ID)
;


-- 
-- TABLE: FOTO_PRODUCTO 
--

ALTER TABLE FOTO_PRODUCTO ADD CONSTRAINT RefPRODUCTO11 
    FOREIGN KEY (PRODUCTO_ID)
    REFERENCES PRODUCTO(PRODUCTO_ID)
;


-- 
-- TABLE: HISTORICO_ESTATUS_PRODUCTO 
--

ALTER TABLE HISTORICO_ESTATUS_PRODUCTO ADD CONSTRAINT RefESTATUS_PRODUCTO8 
    FOREIGN KEY (ESTATUS_PRODUCTO_ID)
    REFERENCES ESTATUS_PRODUCTO(ESTATUS_PRODUCTO_ID)
;

ALTER TABLE HISTORICO_ESTATUS_PRODUCTO ADD CONSTRAINT RefPRODUCTO9 
    FOREIGN KEY (PRODUCTO_ID)
    REFERENCES PRODUCTO(PRODUCTO_ID)
;


-- 
-- TABLE: OFERTA 
--

ALTER TABLE OFERTA ADD CONSTRAINT RefCOMPRADOR15 
    FOREIGN KEY (COMPRADOR_ID)
    REFERENCES COMPRADOR(COMPRADOR_ID)
;

ALTER TABLE OFERTA ADD CONSTRAINT RefPRODUCTO16 
    FOREIGN KEY (PRODUCTO_ID)
    REFERENCES PRODUCTO(PRODUCTO_ID)
;

ALTER TABLE OFERTA ADD CONSTRAINT RefSUBASTA27 
    FOREIGN KEY (SUBASTA_ID)
    REFERENCES SUBASTA(SUBASTA_ID)
;

ALTER TABLE OFERTA ADD CONSTRAINT RefORDEN_DE_COMPRA28 
    FOREIGN KEY (ORDEN_DE_COMPRA_ID)
    REFERENCES ORDEN_DE_COMPRA(ORDEN_DE_COMPRA_ID)
;


-- 
-- TABLE: ORDEN_DE_COMPRA 
--

ALTER TABLE ORDEN_DE_COMPRA ADD CONSTRAINT RefTARJETA18 
    FOREIGN KEY (TARJETA_ID)
    REFERENCES TARJETA(TARJETA_ID)
;


-- 
-- TABLE: PRODUCTO 
--

ALTER TABLE PRODUCTO ADD CONSTRAINT RefVENDEDOR6 
    FOREIGN KEY (VENDEDOR_ID)
    REFERENCES VENDEDOR(VENDEDOR_ID)
;

ALTER TABLE PRODUCTO ADD CONSTRAINT RefCATEGORIA7 
    FOREIGN KEY (CATEGORIA_ID)
    REFERENCES CATEGORIA(CATEGORIA_ID)
;

ALTER TABLE PRODUCTO ADD CONSTRAINT RefESTATUS_PRODUCTO10 
    FOREIGN KEY (ESTATUS_PRODUCTO_ID)
    REFERENCES ESTATUS_PRODUCTO(ESTATUS_PRODUCTO_ID)
;


-- 
-- TABLE: TARJETA 
--

ALTER TABLE TARJETA ADD CONSTRAINT RefCOMPRADOR5 
    FOREIGN KEY (COMPRADOR_ID)
    REFERENCES COMPRADOR(COMPRADOR_ID)
;


-- 
-- TABLE: UBICACION_PAQUETE 
--

ALTER TABLE UBICACION_PAQUETE ADD CONSTRAINT RefFACTURA20 
    FOREIGN KEY (FACTURA_ID)
    REFERENCES FACTURA(FACTURA_ID)
;


-- 
-- TABLE: VENDEDOR 
--

ALTER TABLE VENDEDOR ADD CONSTRAINT RefUSUARIO1 
    FOREIGN KEY (VENDEDOR_ID)
    REFERENCES USUARIO(USUARIO_ID)
;


-- 
-- TABLE: VIDEO_PRODUCTO 
--

ALTER TABLE VIDEO_PRODUCTO ADD CONSTRAINT RefPRODUCTO12 
    FOREIGN KEY (PRODUCTO_ID)
    REFERENCES PRODUCTO(PRODUCTO_ID)
;


