insert into sys_producto.categoria (CATEGORIA_ID, NOMBRE) values (1, 'Squash - Pepper');
insert into sys_producto.categoria (CATEGORIA_ID, NOMBRE) values (2, 'Longos - Greek Salad');
insert into sys_producto.categoria (CATEGORIA_ID, NOMBRE) values (3, 'Pepsi, 355 Ml');
insert into sys_producto.categoria (CATEGORIA_ID, NOMBRE) values (4, 'Herb Du Provence - Primerba');
insert into sys_producto.categoria (CATEGORIA_ID, NOMBRE) values (5, 'Shrimp - Black Tiger 13/15');
insert into sys_producto.categoria (CATEGORIA_ID, NOMBRE) values (6, 'Cheese - Brie,danish');
insert into sys_producto.categoria (CATEGORIA_ID, NOMBRE) values (7, 'Energy Drink - Franks Pineapple');
insert into sys_producto.categoria (CATEGORIA_ID, NOMBRE) values (8, 'Crab - Meat');
insert into sys_producto.categoria (CATEGORIA_ID, NOMBRE) values (9, 'Evaporated Milk - Skim');
insert into sys_producto.categoria (CATEGORIA_ID, NOMBRE) values (10, 'Oil - Margarine');
insert into sys_producto.categoria (CATEGORIA_ID, NOMBRE) values (11, 'Chicken - Base');
insert into sys_producto.categoria (CATEGORIA_ID, NOMBRE) values (12, 'Coffee - Ristretto Coffee Capsule');
insert into sys_producto.categoria (CATEGORIA_ID, NOMBRE) values (13, 'Spice - Peppercorn Melange');
insert into sys_producto.categoria (CATEGORIA_ID, NOMBRE) values (14, 'Potatoes - Idaho 80 Count');
insert into sys_producto.categoria (CATEGORIA_ID, NOMBRE) values (15, 'Chick Peas - Canned');
insert into sys_producto.categoria (CATEGORIA_ID, NOMBRE) values (16, 'Bread - Granary Small Pull');
insert into sys_producto.categoria (CATEGORIA_ID, NOMBRE) values (17, 'Water - Spring Water, 355 Ml');
insert into sys_producto.categoria (CATEGORIA_ID, NOMBRE) values (18, 'Banana');
insert into sys_producto.categoria (CATEGORIA_ID, NOMBRE) values (19, 'Scallops - In Shell');
insert into sys_producto.categoria (CATEGORIA_ID, NOMBRE) values (20, 'Nut - Macadamia');
