insert into sys_usuario.paqueteria (PAQUETERIA_ID, NOMBRE) values (1, 'Rebirth of Mothra III');
insert into sys_usuario.paqueteria (PAQUETERIA_ID, NOMBRE) values (2, 'Spanish Apartment, The (L''auberge espagnole)');
insert into sys_usuario.paqueteria (PAQUETERIA_ID, NOMBRE) values (3, 'Internecine Project, The');
insert into sys_usuario.paqueteria (PAQUETERIA_ID, NOMBRE) values (4, 'Merry Widow, The');
insert into sys_usuario.paqueteria (PAQUETERIA_ID, NOMBRE) values (5, 'Into the West');
insert into sys_usuario.paqueteria (PAQUETERIA_ID, NOMBRE) values (6, 'Howl');
insert into sys_usuario.paqueteria (PAQUETERIA_ID, NOMBRE) values (7, 'At War with the Army');
insert into sys_usuario.paqueteria (PAQUETERIA_ID, NOMBRE) values (8, 'Richie Rich');
insert into sys_usuario.paqueteria (PAQUETERIA_ID, NOMBRE) values (9, 'Hannibal Rising');
insert into sys_usuario.paqueteria (PAQUETERIA_ID, NOMBRE) values (10, 'Foreverland');
insert into sys_usuario.paqueteria (PAQUETERIA_ID, NOMBRE) values (11, 'Steel Toes');
insert into sys_usuario.paqueteria (PAQUETERIA_ID, NOMBRE) values (12, 'Zeisters (Fat Guy Goes Nutzoid)');
insert into sys_usuario.paqueteria (PAQUETERIA_ID, NOMBRE) values (13, 'Speed Racer');
insert into sys_usuario.paqueteria (PAQUETERIA_ID, NOMBRE) values (14, '2016: Obama''s America');
insert into sys_usuario.paqueteria (PAQUETERIA_ID, NOMBRE) values (15, 'Farscape: The Peacekeeper Wars');
insert into sys_usuario.paqueteria (PAQUETERIA_ID, NOMBRE) values (16, 'Kingsman: The Secret Service');
insert into sys_usuario.paqueteria (PAQUETERIA_ID, NOMBRE) values (17, 'One Last Hug');
insert into sys_usuario.paqueteria (PAQUETERIA_ID, NOMBRE) values (18, 'Little Nicholas (Le petit Nicolas)');
insert into sys_usuario.paqueteria (PAQUETERIA_ID, NOMBRE) values (19, '8 Seconds');
insert into sys_usuario.paqueteria (PAQUETERIA_ID, NOMBRE) values (20, 'Passion of Anna, The (Passion, En)');
insert into sys_usuario.paqueteria (PAQUETERIA_ID, NOMBRE) values (21, 'Reservation Road');
insert into sys_usuario.paqueteria (PAQUETERIA_ID, NOMBRE) values (22, 'From Hell It Came');
insert into sys_usuario.paqueteria (PAQUETERIA_ID, NOMBRE) values (23, 'Silent Partner, The');
insert into sys_usuario.paqueteria (PAQUETERIA_ID, NOMBRE) values (24, 'Reindeerspotting - Pako joulumaasta');
insert into sys_usuario.paqueteria (PAQUETERIA_ID, NOMBRE) values (25, 'No Mercy');
insert into sys_usuario.paqueteria (PAQUETERIA_ID, NOMBRE) values (26, 'What Goes Up');
insert into sys_usuario.paqueteria (PAQUETERIA_ID, NOMBRE) values (27, 'Ollie Hopnoodle''s Haven of Bliss');
insert into sys_usuario.paqueteria (PAQUETERIA_ID, NOMBRE) values (28, 'Eye of the Needle');
insert into sys_usuario.paqueteria (PAQUETERIA_ID, NOMBRE) values (29, 'Final, The');
insert into sys_usuario.paqueteria (PAQUETERIA_ID, NOMBRE) values (30, 'Black Orpheus (Orfeu Negro)');
