insert into sys_usuario.ocupacion (OCUPACION_ID, NOMBRE) values (1, 'Librarian');
insert into sys_usuario.ocupacion (OCUPACION_ID, NOMBRE) values (2, 'Biostatistician I');
insert into sys_usuario.ocupacion (OCUPACION_ID, NOMBRE) values (3, 'Cost Accountant');
insert into sys_usuario.ocupacion (OCUPACION_ID, NOMBRE) values (4, 'Compensation Analyst');
insert into sys_usuario.ocupacion (OCUPACION_ID, NOMBRE) values (5, 'Quality Control Specialist');
insert into sys_usuario.ocupacion (OCUPACION_ID, NOMBRE) values (6, 'Statistician II');
insert into sys_usuario.ocupacion (OCUPACION_ID, NOMBRE) values (7, 'Staff Accountant I');
insert into sys_usuario.ocupacion (OCUPACION_ID, NOMBRE) values (8, 'Computer Systems Analyst IV');
insert into sys_usuario.ocupacion (OCUPACION_ID, NOMBRE) values (9, 'Nurse Practicioner');
insert into sys_usuario.ocupacion (OCUPACION_ID, NOMBRE) values (10, 'Civil Engineer');
insert into sys_usuario.ocupacion (OCUPACION_ID, NOMBRE) values (11, 'Financial Analyst');
insert into sys_usuario.ocupacion (OCUPACION_ID, NOMBRE) values (12, 'Teacher');
insert into sys_usuario.ocupacion (OCUPACION_ID, NOMBRE) values (13, 'Teacher');
insert into sys_usuario.ocupacion (OCUPACION_ID, NOMBRE) values (14, 'Quality Engineer');
insert into sys_usuario.ocupacion (OCUPACION_ID, NOMBRE) values (15, 'Account Representative IV');
insert into sys_usuario.ocupacion (OCUPACION_ID, NOMBRE) values (16, 'Teacher');
insert into sys_usuario.ocupacion (OCUPACION_ID, NOMBRE) values (17, 'Dental Hygienist');
insert into sys_usuario.ocupacion (OCUPACION_ID, NOMBRE) values (18, 'Budget/Accounting Analyst I');
insert into sys_usuario.ocupacion (OCUPACION_ID, NOMBRE) values (19, 'Actuary');
insert into sys_usuario.ocupacion (OCUPACION_ID, NOMBRE) values (20, 'Operator');
insert into sys_usuario.ocupacion (OCUPACION_ID, NOMBRE) values (21, 'General Manager');
insert into sys_usuario.ocupacion (OCUPACION_ID, NOMBRE) values (22, 'Chemical Engineer');
insert into sys_usuario.ocupacion (OCUPACION_ID, NOMBRE) values (23, 'Assistant Media Planner');
insert into sys_usuario.ocupacion (OCUPACION_ID, NOMBRE) values (24, 'Accounting Assistant I');
insert into sys_usuario.ocupacion (OCUPACION_ID, NOMBRE) values (25, 'Payment Adjustment Coordinator');
insert into sys_usuario.ocupacion (OCUPACION_ID, NOMBRE) values (26, 'Financial Advisor');
insert into sys_usuario.ocupacion (OCUPACION_ID, NOMBRE) values (27, 'Graphic Designer');
insert into sys_usuario.ocupacion (OCUPACION_ID, NOMBRE) values (28, 'Senior Developer');
insert into sys_usuario.ocupacion (OCUPACION_ID, NOMBRE) values (29, 'Research Associate');
insert into sys_usuario.ocupacion (OCUPACION_ID, NOMBRE) values (30, 'Speech Pathologist');
